# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivado/project_3/project_3.cache/wt [current_project]
set_property parent.project_path F:/vivado/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib {
  F:/vivado/project_3/project_3.srcs/sources_1/new/division.vhd
  F:/vivado/project_3/project_3.srcs/sources_1/new/traffic.vhd
  F:/vivado/project_3/project_3.srcs/sources_1/new/FX4.vhd
}
catch { write_hwdef -file fx4.hwdef }
synth_design -top fx4 -part xc7z010clg400-1
write_checkpoint -noxdef fx4.dcp
catch { report_utilization -file fx4_utilization_synth.rpt -pb fx4_utilization_synth.pb }
